import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

interface CanvaIntegrationCardProps {
  connected: boolean
  brandTemplateId?: string
}

export function CanvaIntegrationCard({ connected, brandTemplateId }: CanvaIntegrationCardProps) {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-base">Canva Invoice Template</CardTitle>
          <Badge variant={connected ? 'success' : 'secondary'}>
            {connected ? 'Connected' : 'Not connected'}
          </Badge>
        </div>
        <CardDescription>
          {connected
            ? 'Every invoice PDF is generated by autofilling your published Canva Brand Template — no manual editing in Canva.'
            : 'Connect a Canva account to have invoice PDFs generated from your Canva Brand Template automatically.'}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        {connected && brandTemplateId && (
          <p className="text-sm text-slate-500">
            Template ID: <code className="text-slate-700">{brandTemplateId}</code>
          </p>
        )}
        <a
          href="/api/canva/connect"
          className="inline-flex h-9 items-center justify-center rounded-md bg-navy px-4 text-sm font-semibold text-white transition-colors hover:bg-navy-hover"
        >
          {connected ? 'Reconnect Canva' : 'Connect Canva'}
        </a>
        {!connected && (
          <p className="text-xs text-slate-400">
            If a generated invoice ever fails to reach Canva, invoices still generate normally
            using the built-in PDF renderer as a fallback.
          </p>
        )}
      </CardContent>
    </Card>
  )
}
